version: '3.8'

services:
  web:
    build: .
    ports:
      - 8081:8080

  db:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

